Repository crystal-lang/shards, pull requests merged in 2021-04, with the labels that each got.

#490 Let `shards build` error if no targets defined
  spec/integration/build_spec.cr
  src/commands/build.cr
Labels: bug

#489 Escape automatic ligatures in AsciiDoc
  docs/shard.yml.adoc
Labels: bug

#494 Add documentation for `shard.override.yml`
  docs/shards.adoc
Labels: feature

#495 Fix to allow empty shard.override.yml
  spec/integration/install_spec.cr
  src/override.cr
Labels: feature

#496 Feature/warn only crystal version
  docs/shard.yml.adoc
  docs/shards.adoc
  spec/integration/install_spec.cr
  spec/integration/spec_helper.cr
  src/cli.cr
  src/commands/command.cr
  src/commands/install.cr
  src/commands/lock.cr
  src/commands/outdated.cr
  src/commands/update.cr
  src/config.cr
  src/molinillo_solver.cr
Labels: enhancement
