Repository crystal-lang/shards, pull requests merged in 2021-02, with the labels that each got.

#471 feat: treat github sources as case insensitive
  spec/integration/spec_helper.cr
  spec/unit/git_resolver_spec.cr
  src/resolvers/git.cr
Labels: enhancement

#466 Improve error message when locked version is missing in source
  spec/integration/install_spec.cr
  src/molinillo_solver.cr
  src/resolvers/resolver.cr
Labels: enhancement

#473 Add `--frozen` and `--without-development` CLI flags
  docs/shards.adoc
  man/shards.1
  spec/integration/install_spec.cr
  spec/integration/list_spec.cr
  src/cli.cr
  src/commands/check.cr
  src/commands/install.cr
  src/commands/list.cr
  src/commands/lock.cr
  src/commands/outdated.cr
  src/commands/update.cr
  src/config.cr
Labels: breaking change, feature

#478 Fix touch install_path to not accidentally create file
  spec/integration/install_spec.cr
  spec/integration/update_spec.cr
  src/commands/command.cr
  src/commands/install.cr
  src/commands/update.cr
Labels: bug
