Repository crystal-lang/shards, pull requests merged in 2022-03, with the labels that each got.

#543 Fix grammar problems
  README.md
  man/shard.yml.5
  man/shards.1
  src/lock.cr
  src/resolvers/git.cr
Labels: bug

#541 Add expanded local path to `shard.yml` error message in `PathResolver`
  spec/integration/install_spec.cr
  spec/integration/spec_helper.cr
  src/resolvers/path.cr
Labels: enhancement

#528 Avoid user defined git template in resolver
  src/resolvers/git.cr
Labels: enhancement

#538 re-enabled ~ support in path resolver
  spec/integration/install_spec.cr
  src/resolvers/path.cr
Labels: enhancement

#539 Add `--jobs` (parallel git fetch)
  docs/shards.adoc
  src/cli.cr
  src/config.cr
  src/molinillo_solver.cr
  src/resolvers/fossil.cr
  src/resolvers/git.cr
  src/resolvers/hg.cr
  src/resolvers/resolver.cr
Labels: enhancement

#549 Add changelog for 0.17.0
  CHANGELOG.md
  VERSION
  docs/shard.yml.adoc
  man/shard.yml.5
  man/shards.1
  shard.yml
Labels: infrastructure
