Repository crystal-lang/shards, pull requests merged in 2024-10, with the labels that each got.

#645 Install mercurial via OS package manager
  .github/workflows/ci.yml
Labels: topic:infrastructure

#646 Fix `GitResolver#valid_repository?`
  src/resolvers/git.cr
Labels: kind:bug, platform:windows

#647 `crystal tool format` with Crystal 1.15.0-dev
  spec/integration/subcommand_spec.cr
  src/package.cr
Labels: kind:chore

#652 Replace deprecated `::sleep(Number)`
  src/molinillo_solver.cr
Labels: kind:chore

#651 Support `.exe` file extension in `Makefile` on MSYS2
  Makefile
Labels: platform:windows

#654 Update CI runners
  .github/workflows/ci.yml
Labels: topic:infrastructure

#653 `devenv update`
  devenv.lock
Labels: topic:infrastructure
