Repository crystal-lang/shards, pull requests merged in 2024-01, with the labels that each got.

#606 Adjust changelog format to follow that of crystal
  CHANGELOG.md
Labels: infrastructure

#607 Fix typos
  docs/shards.adoc
  man/shard.yml.5
  man/shards.1
  spec/integration/outdated_spec.cr
Labels: bug

#609 Add `make help` recipe
  Makefile
  docs.mk
Labels: enhancement

#610 Refactor Makefile phony declaration
  Makefile
  docs.mk
Labels: chore

#608 Fix Makefile incorrect peer target usage
  docs.mk
Labels: bug
